### ISSUE TITLE
Episode 3: What are the SCRUM basics? 

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/teamwork-for-research-software-development#6]
# Objectives:
* Describe the 3 key roles in a Scrum team
* List the different scrum rituals
* List the Scrum artifacts
* Formulate a user story

Use resource 2!

**Comment by JaroCamphuijsen** [comment]
Pr #10 makes a good first start on episode 3, covering the points that are mentioned in this issue's description. I don't think episode 3 is complete yet. Opened a new issue #27 to continue work on this episode.
